AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Description: >
  SAM

  Sample SAM Template for SAM

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst



Resources:
  QuotesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Timeout: 3
      CodeUri: demosamapp/
      Handler: main.quotesfunc
      Runtime: python3.6
      Events:
        Quotes:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /quotes
            Method: get










